### ISSUE TITLE
Contexts and projects with dashes are not correctly recognized

### ISSUE THREAD

**Issue by sanzoghenzo** [samwho/todo-txt-gem#10]
Hi, first of all thanks a lot for this library!
I use contexts that have dashes in the names, and I get only the first part of the name before the dash in the context property. Don't know if it's me using a wrong format or if it's your code that has to be modified (a simple [\w-] in the regex will do the trick).

**Comment by samwho** [comment]
This is now fixed at head thanks to @jgillis01.
