### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by lorentrogers** [samwho/todo-txt-gem#14]
There are no unit tests for these libraries -- there should be some!

I set up a few here: https://github.com/lorentrogers/todo-curses/tree/dev/test I'll submit a PR in a bit.

**Comment by lorentrogers** [comment]
Ha! I just saw that tests exist! (Been a while since I looked through this gem.) I'll do some comparisons between my tests and the ones in here already. May send over a PR for it later.

**Comment by maetl** [comment]
Haha, yeah. Sam did a really good job with test coverage originally. I’ve recently done a bit of refactoring to replace the deprecated RSpec `.should` convention with `expect()` and to separate the syntax parsing/extraction from the main task model.
