### ISSUE TITLE
Relying on rescues for application logic

### ISSUE THREAD

**Issue by lorentrogers** [samwho/todo-txt-gem#19]
Why do we rely on rescues for this? Rubocop doesn't like it, and it seems potentially dangerous -- valid exceptions could go unchecked.

```
lib/todo-txt/syntax.rb:43:7: W: Do not suppress exceptions.
      rescue; end
      ^^^^^^^
lib/todo-txt/syntax.rb:50:7: W: Do not suppress exceptions.
      rescue; end
      ^^^^^^^
lib/todo-txt/syntax.rb:57:7: W: Do not suppress exceptions.
      rescue; end
      ^^^^^^^
```

Could this not be handled via return values?

**Comment by maetl** [comment]
This could definitely be changed if there is a more idiomatic code style that doesn’t use exceptions for logic/flow control.

I recently extracted `Syntax` out of the `Task` class specifically to make refactorings like this more straightforward in future.

**Comment by lorentrogers** [comment]
I noticed the new `Syntax` logic -- very nice. It made reading through the `Task` class a lot easier. And, I figure the thinking was to have it split out in case we want to use it elsewhere? (The syntax would track whatever the latest todo.txt spec is.)

And cool; I've got some local code I'm working on that removes the `rescue` clauses. I'll split them out into a PR soon.

**Comment by lorentrogers** [comment]
Ok, so after much tinkering, I figured out why the rescues were there in the first place. Because it should only return a date if it's a valid calendar entry, the `Date.parse` method is used to make the conversion from a `String` into a `Date`. But, if it's not a valid date (e.g. 2016-35-35,) then it will throw an error. (Not just return nil.) That error: `ArgumentError`. 

To help clarify this, I put together a patch in #21 that refactors things a bit and adds docs to these methods. Hopefully the more specific `rescue` statement won't be overly broad. (Is there a good way to make this even more specific to the `ArgumentError: invalid date` error?)
