### ISSUE TITLE
Require a more civilized version of ruby

### ISSUE THREAD

**Issue by lorentrogers** [samwho/todo-txt-gem#22]
Sounds like this gem is in need of a min-Ruby-version update: https://github.com/samwho/todo-txt-gem/pull/16#issuecomment-204940606

What would be a better minimum? The Travis builds are running `2.0+`: https://github.com/samwho/todo-txt-gem/pull/16#issuecomment-204846129

**Comment by maetl** [comment]
Closed via 2a4597c. I’ve set the minimum required version to `2.0` to match the Travis configuration. Might be a good idea to look at going to `2.1+` if and when the community moves over en masse.
