### ISSUE TITLE
x-Marked tasks without a completion date should be considered ‘done’

### ISSUE THREAD

**Issue by maetl** [samwho/todo-txt-gem#28]
In the wild, it’s not uncommon to see completed tasks marked without any associated dates:

```
x Fix task completion bug
```

Whether or not this is correct is unclear from the spec. But it is a naive and simple use case which seems like it should be supported by default.

**Comment by lorentrogers** [comment]
Agreed; perhaps a good case for an option? https://github.com/samwho/todo-txt-gem/issues/27#issuecomment-205250965

**Comment by maetl** [comment]
Fixed by 134f4867db0eb1aa218cefc8ace2fc0887abaa3e.
